# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-05-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_DefaultBuyPriceIzZero'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_reminder_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Date of the last reminder'),
        ),
    ]
